- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    elasticsearch:
      domain_name: "playbook-test"
      stack_prefix: "role-test-"
      template: "build/test.json"
  roles: 
    - role: elasticsearch

