---
- name: Create ElasticSearch Template
  template: 
    src: es.json.j2 
    dest: "{{ elasticsearch.template }}"

- name: Run cloudformation
  cloudformation:
    template: "{{ elasticsearch.template }}"
    region: "{{ region }}"
    stack_name: "{{ environ }}-{{ elasticsearch.stack_prefix | default(omit) }}elasticsearch"
    template_parameters: 
      DomainName: "{{ elasticsearch.domain_name }}"
  
